apiVersion: network.openstack.org/v1beta1
kind: NetConfig
metadata:
  name: openstacknetconfig
  namespace: openstack
spec:
  networks:
    - name: ctlplane-rhoso
      dnsDomain: ctlplane-rhoso.osptest.test.metalkube.org
      subnets:
        - name: ctlplane
          allocationRanges:
          - end: 172.22.0.149
            start: 172.22.0.100
          cidr: 172.22.0.0/24
          gateway: 172.22.0.1
          routes: []
          vlan: 0
    - name: internalapi-rhoso
      dnsDomain: internalapi-rhoso.osptest.test.metalkube.org
      subnets:
        - name: internalapi
          allocationRanges:
          - end: 172.17.0.149
            start: 172.17.0.100
          cidr: 172.17.0.0/24
          routes: []
          vlan: 20
    - name: external-rhoso
      dnsDomain: external-rhoso.osptest.test.metalkube.org
      subnets:
        - name: external
          allocationRanges:
            - end: 10.0.0.149
              start: 10.0.0.100
          cidr: 10.0.0.0/24
          gateway: 10.0.0.1
          routes: []          
          vlan: 0
    - name: storage-rhoso
      dnsDomain: storage-rhoso.osptest.test.metalkube.org
      subnets:
        - name: storage
          allocationRanges:
          - end: 172.18.0.149
            start: 172.18.0.100
          cidr: 172.18.0.0/24
          routes: []
          vlan: 30
    - name: storagemgmt-rhoso
      dnsDomain: storagemgmt-rhoso.osptest.test.metalkube.org
      subnets:
        - name: storagemgmt-rhoso
          allocationRanges:
          - end: 172.19.0.149
            start: 172.19.0.100
          cidr: 172.19.0.0/24
          routes: []
          vlan: 40
    - name: tenant-rhoso
      dnsDomain: tenant-rhoso.osptest.test.metalkube.org
      subnets:
        - name: tenant-rhoso
          allocationRanges:
          - end: 172.20.0.149
            start: 172.20.0.100
          cidr: 172.20.0.0/24
          routes: []
          vlan: 50
