apiVersion: v1
kind: Pod
metadata:
  name: mariadb-copy-data
  namespace: ${NAMESPACE}
  annotations:
    openshift.io/scc: anyuid
    k8s.v1.cni.cncf.io/networks: |-
      [
        {
          "name": "${NETWORK}", 
          "namespace": "${NAMESPACE}", 
          "ips": ["172.17.0.99/24"] 
        }
      ]
  labels:
    app: adoption
spec:
  nodeName: ${TARGET_NODE}
  containers:
  - image: ${IMAGE}
    command: [ "sh", "-c", "sleep infinity"]
    name: adoption
    volumeMounts:
    - mountPath: /backup
      name: mariadb-data
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop: ALL
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  volumes:
  - name: mariadb-data
    persistentVolumeClaim:
      claimName: mariadb-data
