apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: ctlplane-osp18
  namespace: ${OSP18_NAMESPACE}
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "ctlplane-osp18",
      "type": "bridge",
      "master": "br-ctlplane",
      "ipam": {
        "type": "whereabouts",
        "range": "172.22.0.0/24",
        "range_start": "172.22.0.30",
        "range_end": "172.22.0.70"
      }
    }
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: internalapi-osp18
  namespace: ${OSP18_NAMESPACE}
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "internalapi-osp18",
      "type": "macvlan",
      "master": "enp7s0.20",
      "ipam": {
        "type": "whereabouts",
        "range": "172.17.0.0/24",
        "range_start": "172.17.0.30",
        "range_end": "172.17.0.70"
      }
    }
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: external-osp18
  namespace: ${OSP18_NAMESPACE}
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "external-osp18",
      "type": "macvlan",
      "master": "br-external",
      "ipam": {
        "type": "whereabouts",
        "range": "10.0.0.0/24",
        "range_start": "10.0.0.30",
        "range_end": "10.0.0.70"
      }
    }
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: storage-osp18
  namespace: ${OSP18_NAMESPACE}
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "storage-osp18",
      "type": "macvlan",
      "master": "enp7s0.30",
      "ipam": {
        "type": "whereabouts",
        "range": "172.18.0.0/24",
        "range_start": "172.18.0.30",
        "range_end": "172.18.0.70"
      }
    }
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: storagemgmt-osp18
  namespace: ${OSP18_NAMESPACE}
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "storagemgmt-osp18",
      "type": "macvlan",
      "master": "enp7s0.40",
      "ipam": {
        "type": "whereabouts",
        "range": "172.19.0.0/24",
        "range_start": "172.19.0.30",
        "range_end": "172.19.0.70"
      }
    }
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: tenant-osp18
  namespace: ${OSP18_NAMESPACE}
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "tenant-osp18",
      "type": "macvlan",
      "master": "enp7s0.50",
      "ipam": {
        "type": "whereabouts",
        "range": "172.20.0.0/24",
        "range_start": "172.20.0.30",
        "range_end": "172.20.0.70"
      }
    }
