apiVersion: network.openstack.org/v1beta1
kind: NetConfig
metadata:
  name: openstacknetconfig
  namespace: ${OSP18_NAMESPACE}
spec:
  networks:
    - name: ctlplane-osp18
      dnsDomain: ctlplane-osp18.osptest.test.metalkube.org
      subnets:
        - name: ctlplane-osp18
          allocationRanges:
          - end: 172.22.0.149
            start: 172.22.0.100
          cidr: 172.22.0.0/24
          gateway: 172.22.0.1
          routes: []
          vlan: 0
    - name: internalapi-osp18
      dnsDomain: internalapi-osp18.osptest.test.metalkube.org
      subnets:
        - name: internalapi-osp18
          allocationRanges:
          - end: 172.17.0.149
            start: 172.17.0.100
          cidr: 172.17.0.0/24
          routes: []
          vlan: 20
    - name: external-osp18
      dnsDomain: external-osp18.osptest.test.metalkube.org
      subnets:
        - name: external-osp18
          allocationRanges:
            - end: 10.0.0.149
              start: 10.0.0.100
          cidr: 10.0.0.0/24
          gateway: 10.0.0.1
          routes: []          
          vlan: 0
    - name: storage-osp18
      dnsDomain: storage-osp18.osptest.test.metalkube.org
      subnets:
        - name: storage-osp18
          allocationRanges:
          - end: 172.18.0.149
            start: 172.18.0.100
          cidr: 172.18.0.0/24
          routes: []
          vlan: 30
    - name: storagemgmt-osp18
      dnsDomain: storagemgmt-osp18.osptest.test.metalkube.org
      subnets:
        - name: storagemgmt-osp18
          allocationRanges:
          - end: 172.19.0.149
            start: 172.19.0.100
          cidr: 172.19.0.0/24
          routes: []
          vlan: 40
    - name: tenant-osp18
      dnsDomain: tenant-osp18.osptest.test.metalkube.org
      subnets:
        - name: tenant-osp18
          allocationRanges:
          - end: 172.20.0.149
            start: 172.20.0.100
          cidr: 172.20.0.0/24
          routes: []
          vlan: 50
