apiVersion: network.openstack.org/v1beta1
kind: NetConfig
metadata:
  name: openstacknetconfig
  namespace: ${OSP18_NAMESPACE}
spec:
  networks:
    - name: ctlplane
      dnsDomain: ctlplane.osptest.test.metalkube.org
      subnets:
        - name: ctlplane
          allocationRanges:
          - end: 172.22.0.149
            start: 172.22.0.100
          cidr: 172.22.0.0/24
          gateway: 172.22.0.1
          routes: []
          vlan: 0
    - name: internalapi
      dnsDomain: internalapi.osptest.test.metalkube.org
      subnets:
        - name: internalapi
          allocationRanges:
          - end: 172.17.0.149
            start: 172.17.0.100
          cidr: 172.17.0.0/24
          routes: []
          vlan: 20
    - name: external
      dnsDomain: external.osptest.test.metalkube.org
      subnets:
        - name: external
          allocationRanges:
            - end: 10.0.0.149
              start: 10.0.0.100
          cidr: 10.0.0.0/24
          gateway: 10.0.0.1
          routes: []          
          vlan: 0
    - name: storage
      dnsDomain: storage.osptest.test.metalkube.org
      subnets:
        - name: storage
          allocationRanges:
          - end: 172.18.0.149
            start: 172.18.0.100
          cidr: 172.18.0.0/24
          routes: []
          vlan: 30
    - name: storagemgmt
      dnsDomain: storagemgmt.osptest.test.metalkube.org
      subnets:
        - name: storagemgmt
          allocationRanges:
          - end: 172.19.0.149
            start: 172.19.0.100
          cidr: 172.19.0.0/24
          routes: []
          vlan: 40
    - name: tenant
      dnsDomain: tenant.osptest.test.metalkube.org
      subnets:
        - name: tenant
          allocationRanges:
          - end: 172.20.0.149
            start: 172.20.0.100
          cidr: 172.20.0.0/24
          routes: []
          vlan: 50
