apiVersion: v1
kind: Pod
metadata:
  name: ovn-copy-data
  namespace: ${OSP18_NAMESPACE}
  annotations:
    openshift.io/scc: anyuid
    k8s.v1.cni.cncf.io/networks: |-
      [
        {
          "name": "internalapi-osp18", 
          "namespace": "${OSP18_NAMESPACE}"
        }
      ]
  labels:
    app: adoption
spec:
  nodeSelector:
    type: openstack
  containers:
  - image: ${OVSDB_IMAGE}
    command: [ "sh", "-c", "sleep infinity"]
    name: adoption
    volumeMounts:
    - mountPath: /backup
      name: ovn-data
    - mountPath: /etc/pki/tls/misc
      name: ovn-data-cert
      readOnly: true
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop: ALL
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  volumes:
  - name: ovn-data
    persistentVolumeClaim:
      claimName: ovn-data
  - name: ovn-data-cert
    secret:
      secretName: ovn-data-cert
