apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ovn-data
  namespace: ${OSP18_NAMESPACE}
spec:
  storageClassName: ${STORAGE_CLASS}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
