apiVersion: v1
kind: Pod
metadata:
  annotations:
    # k8s.ovn.org/pod-networks: '{"default":{"ip_addresses":["10.130.1.1/23"],"mac_address":"0a:58:0a:82:01:01","gateway_ips":["10.130.0.1"],"routes":[{"dest":"10.128.0.0/14","nextHop":"10.130.0.1"},{"dest":"172.30.0.0/16","nextHop":"10.130.0.1"},{"dest":"100.64.0.0/16","nextHop":"10.130.0.1"}],"ip_address":"10.130.1.1/23","gateway_ip":"10.130.0.1"}}'
    # k8s.v1.cni.cncf.io/network-status: |-
    #   [{
    #       "name": "ovn-kubernetes",
    #       "interface": "eth0",
    #       "ips": [
    #           "10.130.1.1"
    #       ],
    #       "mac": "0a:58:0a:82:01:01",
    #       "default": true,
    #       "dns": {}
    #   },{
    #       "name": "osp18/ctlplane-osp18",
    #       "interface": "ctlplane-osp18",
    #       "ips": [
    #           "172.22.0.30"
    #       ],
    #       "mac": "42:7d:a2:fa:95:11",
    #       "dns": {}
    #   }]
#    k8s.v1.cni.cncf.io/networks: '[{"name":"ctlplane-osp18","namespace":"osp18","interface":"ctlplane-osp18"}]'
    k8s.v1.cni.cncf.io/networks: '[{"name":"ctlplane-osp18","namespace":"osp18","interface":"ctlplane-osp18"}]'
    openshift.io/scc: privileged
    seccomp.security.alpha.kubernetes.io/pod: runtime/default
  labels:
    app: centos
  name: zorro
  namespace: osp18
spec:
  containers:
  - name: fedora
    image: wbitt/network-multitool:openshift-extra
    command: [ "/bin/bash", "-c", "--"]
    args: [ "while true; do sleep 3000; done;" ]
    imagePullPolicy: IfNotPresent
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities:
        add:
        - NET_ADMIN
      # capabilities:
      #   drop:
      #   - ALL
      #   add:
      #   - ALL
#      runAsNonRoot: true
#      runAsUser: 1000740000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: ostest-master-1
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1000740000
    seLinuxOptions:
      level: s0:c27,c19
    seccompProfile:
      type: RuntimeDefault
  serviceAccount: openstack
  serviceAccountName: openstack
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
